### ISSUE TITLE
How to use this API through LAN?

### ISSUE THREAD

**Issue by yamosin** [theroyallab/tabbyAPI#16]
I have a 4x3090 server in another room. After starting, I can connect through remote desktop and use sillytavern's tabbyAPI on the server itself, but I cannot connect to the server IP: 5000 (default port) on my computer, connect rejected, linking the server ip:port/docs through the web page is also rejected.
On my computer, I can connect to the server through oobabooga's API. Do I need to set up anything else?

**Comment by bdashore3** [comment]
Hi there! The file `config_sample.yml` (which should be your config.yml) has the following entry under the network block:

```yaml
network:
  # The IP to host on (default: 127.0.0.1).
  # Use 0.0.0.0 to expose on all network adapters
  host: 127.0.0.1

  # The port to host on (default: 5000)
  port: 5000
  ```

This line: `# Use 0.0.0.0 to expose on all network adapters` gives the answer to your problem. Set the `host` line to `0.0.0.0` and it should work.
