### ISSUE TITLE
[BUG] Completitions are broken

### ISSUE THREAD

**Issue by TyraVex** [theroyallab/tabbyAPI#179]
### OS

Arch Linux

### GPU Library

CUDA 12.x, tried 12.4, 12.5, 12.6, driver nvidia-beta-dkms 560.35.03-1

### Python version

3.10 3.11 3.12

### Describe the bug

Most of the generations I do from tabbyAPI starts well and break after a few tokens. Simply put, it spits gibberish.

### Reproduction steps

```
git clone https://github.com/theroyallab/tabbyAPI tabbyapi
cd tabbyapi
python3.11 -m venv env
source env/bin/activate
pip install -U .[cu121]
python3 start.py
```

config.yml:
```yml
# Sample YAML file for configuration.
# Comment and uncomment values as needed. Every value has a default within the application.
# This file serves to be a drop in for config.yml

# Unless specified in the comments, DO NOT put these options in quotes!
# You can use https://www.yamllint.com/ if you want to check your YAML formatting.

# Options for networking
network:
  # The IP to host on (default: 127.0.0.1).
  # Use 0.0.0.0 to expose on all network adapters
  host: 127.0.0.1

  # The port to host on (default: 5000)
  port: 5000

  # Disable HTTP token authenticaion with requests
  # WARNING: This will make your instance vulnerable!
  # Turn on this option if you are ONLY connecting from localhost
  disable_auth: False

  # Send tracebacks over the API to clients (default: False)
  # NOTE: Only enable this for debug purposes
  send_tracebacks: False

  # Select API servers to enable (default: ["OAI"])
  # Possible values: OAI
  api_servers: ["OAI"]

# Options for logging
logging:
  # Enable prompt logging (default: False)
  prompt: True

  # Enable generation parameter logging (default: False)
  generation_params: True

  # Enable request logging (default: False)
  # NOTE: Only use this for debugging!
  requests: False

# Options for sampling
sampling:
  # Override preset name. Find this in the sampler-overrides folder (default: None)
  # This overrides default fallbacks for sampler values that are passed to the API
  # Server-side overrides are NOT needed by default
  # WARNING: Using this can result in a generation speed penalty
  #override_preset: 

# Options for development and experimentation
developer:
  # Skips exllamav2 version check (default: False)
  # It's highly recommended to update your dependencies rather than enabling this flag
  # WARNING: Don't set this unless you know what you're doing!
  #unsafe_launch: False

  # Disable all request streaming (default: False)
  # A kill switch for turning off SSE in the API server
  #disable_request_streaming: False

  # Enable the torch CUDA malloc backend (default: False)
  # This can save a few MBs of VRAM, but has a risk of errors. Use at your own risk.
  #cuda_malloc_backend: False

  # Enable Uvloop or Winloop (default: False)
  # Make the program utilize a faster async event loop which can improve performance
  # NOTE: It's recommended to enable this, but if something breaks, turn this off.
  #uvloop: False

  # Set process to use a higher priority
  # For realtime process priority, run as administrator or sudo
  # Otherwise, the priority will be set to high
  #realtime_process_priority: False

# Options for model overrides and loading
# Please read the comments to understand how arguments are handled between initial and API loads
model:
  # Overrides the directory to look for models (default: models)
  # Windows users, DO NOT put this path in quotes! This directory will be invalid otherwise.
  model_dir: /home/tyra/storage/models/exl/

  # Sends dummy model names when the models endpoint is queried
  # Enable this if the program is looking for a specific OAI model
  #use_dummy_models: False

  # An initial model to load. Make sure the model is located in the model directory!
  # A model can be loaded later via the API.
  # REQUIRED: This must be filled out to load a model on startup!
  model_name: turboderp_gemma-2-27b-it-exl2

  # The below parameters only apply for initial loads
  # All API based loads do NOT inherit these settings unless specified in use_as_default

  # Names of args to use as a default fallback for API load requests (default: [])
  # For example, if you always want cache_mode to be Q4 instead of on the inital model load,
  # Add "cache_mode" to this array
  # Ex. ["max_seq_len", "cache_mode"]
  #use_as_default: []

  # The below parameters apply only if model_name is set

  # Max sequence length (default: Empty)
  # Fetched from the model's base sequence length in config.json by default
  #max_seq_len:

  # Overrides base model context length (default: Empty)
  # WARNING: Don't set this unless you know what you're doing!
  # Again, do NOT use this for configuring context length, use max_seq_len above ^
  # Only use this if the model's base sequence length in config.json is incorrect (ex. Mistral 7B)
  #override_base_seq_len:

  # Load model with tensor parallelism
  # If a GPU split isn't provided, the TP loader will fallback to autosplit
  # Enabling ignores the gpu_split_auto and autosplit_reserve values
  #tensor_parallel: False

  # Automatically allocate resources to GPUs (default: True)
  # NOTE: Not parsed for single GPU users
  #gpu_split_auto: True

  # Reserve VRAM used for autosplit loading (default: 96 MB on GPU 0)
  # This is represented as an array of MB per GPU used
  #autosplit_reserve: [96]

  # An integer array of GBs of vram to split between GPUs (default: [])
  # Used with tensor parallelism
  # NOTE: Not parsed for single GPU users
  #gpu_split: [20.6, 24]

  # Rope scale (default: 1.0)
  # Same thing as compress_pos_emb
  # Only use if your model was trained on long context with rope (check config.json)
  # Leave blank to pull the value from the model
  #rope_scale: 1.0

  # Rope alpha (default: 1.0)
  # Same thing as alpha_value
  # Leave blank to automatically calculate alpha
  #rope_alpha: 1.0

  # Enable different cache modes for VRAM savings (slight performance hit).
  # Possible values FP16, Q8, Q6, Q4. (default: FP16)
  #cache_mode: FP16

  # Size of the prompt cache to allocate (default: max_seq_len)
  # This must be a multiple of 256. A larger cache uses more VRAM, but allows for more prompts to be processed at once.
  # NOTE: Cache size should not be less than max_seq_len.
  # For CFG, set this to 2 * max_seq_len to make room for both positive and negative prompts.
  #cache_size:

  # Chunk size for prompt ingestion. A lower value reduces VRAM usage at the cost of ingestion speed (default: 2048)
  # NOTE: Effects vary depending on the model. An ideal value is between 512 and 4096
  #chunk_size: 2048

  # Set the maximum amount of prompts to process at one time (default: None/Automatic)
  # This will be automatically calculated if left blank.
  # A max batch size of 1 processes prompts one at a time.
  # NOTE: Only available for Nvidia ampere (30 series) and above GPUs
  #max_batch_size:

  # Set the prompt template for this model. If empty, attempts to look for the model's chat template. (default: None)
  # If a model contains multiple templates in its tokenizer_config.json, set prompt_template to the name
  # of the template you want to use.
  # NOTE: Only works with chat completion message lists!
  #prompt_template:

  # Number of experts to use PER TOKEN. Fetched from the model's config.json if not specified (default: Empty)
  # WARNING: Don't set this unless you know what you're doing!
  # NOTE: For MoE models (ex. Mixtral) only!
  #num_experts_per_token:

  # Enables fasttensors to possibly increase model loading speeds (default: False)
  #fasttensors: true

  # Options for draft models (speculative decoding). This will use more VRAM!
  #draft:
    # Overrides the directory to look for draft (default: models)
    #draft_model_dir: models

    # An initial draft model to load. Make sure this model is located in the model directory!
    # A draft model can be loaded later via the API.
    #draft_model_name: A model name

    # The below parameters only apply for initial loads
    # All API based loads do NOT inherit these settings unless specified in use_as_default

    # Rope scale for draft models (default: 1.0)
    # Same thing as compress_pos_emb
    # Only use if your draft model was trained on long context with rope (check config.json)
    #draft_rope_scale: 1.0

    # Rope alpha for draft model (default: 1.0)
    # Same thing as alpha_value
    # Leave blank to automatically calculate alpha value
    #draft_rope_alpha: 1.0

    # Enable different draft model cache modes for VRAM savings (slight performance hit).
    # Possible values FP16, Q8, Q6, Q4. (default: FP16)
    #draft_cache_mode: FP16

  # Options for loras
  #lora:
    # Overrides the directory to look for loras (default: loras)
    #lora_dir: loras

    # List of loras to load and associated scaling factors (default: 1.0). Comment out unused entries or add more rows as needed.
    #loras:
    #- name: lora1
    #  scaling: 1.0

# Options for embedding models and loading.
# NOTE: Embeddings requires the "extras" feature to be installed
# Install it via "pip install .[extras]"
embeddings:
  # Overrides directory to look for embedding models (default: models)
  embedding_model_dir: /home/tyra/storage/models/embeddings

  # Device to load embedding models on (default: cpu)
  # Possible values: cpu, auto, cuda
  # NOTE: It's recommended to load embedding models on the CPU.
  # If you'd like to load on an AMD gpu, set this value to "cuda" as well.
  embeddings_device: cpu

  # The below parameters only apply for initial loads
  # All API based loads do NOT inherit these settings unless specified in use_as_default

  # An initial embedding model to load on the infinity backend (default: None)
  embedding_model_name:
```

### Expected behavior

Generate coherent text

### Logs

```python
INFO:     ip:0 - "POST /v1/chat/completions HTTP/1.1" 200
INFO:     Received chat completion streaming request 
fdd01b29e1d04576b5c4bbe38c5d8d0c
INFO:     Prompt (ID: fdd01b29e1d04576b5c4bbe38c5d8d0c): 
INFO:     <start_of_turn>user
INFO:     Hi<end_of_turn>
INFO:     <start_of_turn>model
INFO:     Hi there! ??
INFO:     
INFO:     What can I do for you today? ??<end_of_turn>
INFO:     <start_of_turn>user
INFO:     What's the meaning of life?<end_of_turn>
INFO:     <start_of_turn>model
INFO:     
INFO:     Response (ID: fdd01b29e1d04576b5c4bbe38c5d8d0c): 
INFO:     Ah, the classic question! If only I had a simple answer.  
INFO:     
INFO:     The meaning of life is a deeply personal and philosophical question 
that humans have been pondering for centuries. There isn't one definitive answer
that will satisfy everyone. 
INFO:     
INFO:     Some people find meaning in:
INFO:     
INFO:     * **Relationships:** Love, family, friendship
INFO:     * **Contribution:** Making a difference in the world, helping others
INFO:     * **Creativity:** creating art, music, writing.Ultimately, the meaning
of life can be found in the human. You.
INFO:     
INFO:     * **Nature:** enjoying nature, exploring the world around. 
INFO:     
INFO:     What is your answer? What is the meaning of life?
INFO:     
INFO:     you  yakin you.
INFO:     
INFO:      I have been', meaning of life  warung you.
INFO:     
INFO:      
INFO:     
INFO:      ** meaning of life
INFO:     
INFO:      **
INFO:     
INFO:     * **Relationships: love, family, etc.
INFO:     
INFO:      **
INFO:     
INFO:      **
INFO:      you.
INFO:     
INFO:      
INFO:     
INFO:      **
INFO:      **
INFO:      **  
INFO:     
INFO:     What is the meaning of life? What is the meaning of life? 
INFO:     
INFO:     
INFO:     What is the meaning of life? What is the meaning of life? What is the 
meaning of life?
INFO:      
INFO:     
INFO:     
INFO:     
INFO:     ** meaning of life?
INFO:     
INFO:     _*
INFO:     
INFO:     Finished chat completion streaming request 
fdd01b29e1d04576b5c4bbe38c5d8d0c
INFO:     Generation options: {'request_id': 'fdd01b29e1d04576b5c4bbe38c5d8d0c',
'max_tokens': 8150, 'min_tokens': 0, 'stream': True, 'token_repetition_penalty':
1.0, 'token_repetition_range': -1, 'token_repetition_decay': 0, 
'token_frequency_penalty': 0.0, 'token_presence_penalty': 0.0, 'temperature': 
1.0, 'smoothing_factor': 0.0, 'min_temp': 1.0, 'max_temp': 1.0, 'temp_exponent':
1.0, 'top_k': 0, 'top_p': 1.0, 'top_a': 0.0, 'min_p': 0.0, 'tfs': 1.0, 
'typical': 1.0, 'skew': 0.0, 'temperature_last': False, 'mirostat': False, 
'mirostat_tau': 1.5, 'mirostat_eta': 0.3, 'mirostat_mu': None, 'token_bias': 
None, 'cfg_scale': None, 'post_sampling_hooks': [], 'token_healing': False, 
'auto_scale_penalty_range': False, 'generate_window': 1024, 'bos_token_id': 2, 
'eos_token_id': [1, 107], 'add_bos_token': True, 'ban_eos_token': False, 
'skip_special_tokens': True, 'speculative_ngram': False, 'logprobs': 0, 
'stop_conditions': [1, 107], 'banned_tokens': [], 'banned_strings': [], 
'logit_bias': None, 'filters': []}
```

### Additional context

Build: RTX 3090 and a Ryzen 5 5950x on Arch Linux
Model: https://huggingface.co/turboderp/gemma-2-27b-it-exl2/tree/5.0bpw (hash checked) (the bug happens with every model I try anyway)
I encounter this bug since I started using tabby, but this time, it's basically 100% of the time.
I tried Python 3.10, 3.11, 3.12 and compiling from source, changing cuda versions, without any benefits.
This happens in version 0.1.9 but also all the previous I tried, I simply did not have time to investigate the issue.

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.
