### ISSUE TITLE
[REQUEST] Allow server-side configuration & override of generation parameters

### ISSUE THREAD

**Issue by KMouratidis** [theroyallab/tabbyAPI#298]
### Problem

When using tabby with other tools (e.g. I was using [OpenHands](https://github.com/All-Hands-AI/OpenHands)) I noticed that they sometimes use 0 temperature which tabby then sets to `1`:

```
2025-03-07 14:41:54.288 WARNING:  Temperature is set to 0. Overriding temp,
top_k, top_p, and typical to 1.0, 1, 0, and 0.
```

This may not always be ideal.

### Solution

Under the `model` configuration, an option could be added have some parameters always overridden, e.g. it could look like this:

```
model:
    ...

    # Default & override these values for all generation requests
    generation_overrides:
        temperature: 0.7
        top_p: 0.9
        # top_k not defined -> according to request or existing default
```

### Alternatives

- Modifying options on the third-party tools side -> works for some, e.g. OpenWebUI *and OpenHands*, but maybe not all
- Proxy API in front of tabby that alters these parameters
- ???

### Explanation

Some models work best with certain settings, but tuning those settings may not be easy/possible on the client / third-party tool side. This feature could help solve this.

### Acknowledgements

- [x] I have looked for similar requests before submitting this one.
- [x] I understand that the developers have lives and my issue will be answered when possible.
- [x] I understand the developers of this program are human, and I will make my requests politely.
