### ISSUE TITLE
[BUG] Sampler presets do not load

### ISSUE THREAD

**Issue by frenzybiscuit** [theroyallab/tabbyAPI#315]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

Create a custom sampler preset in the sampler_overrides folder called presets.yml.

Try loading in TabbyAPI. It doesn't load.

Following error:

WARNING:  Sampler override file named "presets.yml" was not found. Make sure it's located in the sampler_overrides folder.

```
llm@fedora:/mnt/nvme1n1p1/tabbyapi/tabbyAPI$ ls -l sampler_overrides
total 8
-rw-r--r--. 1 llm llm  265 Mar 28 09:03 presets.yml
-rw-r--r--. 1 llm llm 2745 Mar 23 15:46 sample_preset.yml
```

Contents of file:
```

max_tokens:
  override: 400
  force: false
temperature:
  override: 1.0
  force: false
min_p:
  override: 0.025
  force: false
dry_multiplier:
  override: 0.8
  force: false
dry_base:
  override: 1.74
  force: false
dry_allowed_length:
  override: 4
  force: false
```

### Reproduction steps

.

### Expected behavior

works as expected

### Acknowledgements

- [x] I have looked for similar issues before submitting this one.
- [x] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [x] I understand that the developers have lives and my issue will be answered when possible.
- [x] I understand the developers of this program are human, and I will ask my questions politely.
