### ISSUE TITLE
[BUG] latest docker image seems to be broken

### ISSUE THREAD

**Issue by atisharma** [theroyallab/tabbyAPI#323]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.10

### Describe the bug

I just pulled the latest docker image, which seems to be broken.

Using the same config that worked before, I get an import error.

```
/srv/tabby-api # docker-compose up mistral-large
[+] Running 1/0
 ✔ Container tabby-api-mistral-large-1  Created                                                                                                    [...]
mistral-large-1  | ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so)
mistral-large-1 exited with code 0
```

The same thing happens with my qwq config.

### Reproduction steps

- pull latest docker image
- use the following docker-compose.yml to start the service

```
services:
  mistral-large:
    restart: always
    image: ghcr.io/theroyallab/tabbyapi:latest
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.0.0.102:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NAME=mistral-large
    volumes:
      - /srv:/srv
      - /srv/tabby-api/configs/mistral-large.yml:/app/config.yml
      - /srv/tabby-api/api_tokens.yml:/app/api_tokens.yml
      - /srv/tabby-api/sampler_overrides:/app/sampler_overrides
      - /srv/tabby-api/templates:/app/templates
      - /srv/tabby-api/models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '3']
              #count: all
              capabilities: [gpu]
```

### Expected behavior

The import in the docker container should work and the service should come up.

### Logs

```
/srv/tabby-api # docker-compose up mistral-large
[+] Running 1/0
 ✔ Container tabby-api-mistral-large-1  Created                                                                                                    0.0s 
Attaching to mistral-large-1
mistral-large-1  | Traceback (most recent call last):
mistral-large-1  |   File "/app/main.py", line 12, in <module>
mistral-large-1  |     from common import gen_logging, sampling, model
mistral-large-1  |   File "/app/common/model.py", line 15, in <module>
mistral-large-1  |     from backends.base_model_container import BaseModelContainer
mistral-large-1  |   File "/app/backends/base_model_container.py", line 13, in <module>
mistral-large-1  |     from common.multimodal import MultimodalEmbeddingWrapper
mistral-large-1  |   File "/app/common/multimodal.py", line 1, in <module>
mistral-large-1  |     from backends.exllamav2.vision import get_image_embedding
mistral-large-1  |   File "/app/backends/exllamav2/vision.py", line 21, in <module>
mistral-large-1  |     from exllamav2.generator import ExLlamaV2MMEmbedding
mistral-large-1  |   File "/usr/local/lib/python3.10/dist-packages/exllamav2/__init__.py", line 3, in <module>
mistral-large-1  |     from exllamav2.model import ExLlamaV2
mistral-large-1  |   File "/usr/local/lib/python3.10/dist-packages/exllamav2/model.py", line 39, in <module>
mistral-large-1  |     from exllamav2.attn import ExLlamaV2Attention, has_flash_attn, has_xformers
mistral-large-1  |   File "/usr/local/lib/python3.10/dist-packages/exllamav2/attn.py", line 36, in <module>
mistral-large-1  |     import flash_attn
mistral-large-1  |   File "/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py", line 3, in <module>
mistral-large-1  |     from flash_attn.flash_attn_interface import (
mistral-large-1  |   File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 15, in <module>
mistral-large-1  |     import flash_attn_2_cuda as flash_attn_gpu
mistral-large-1  | ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so)
mistral-large-1 exited with code 0
```

### Acknowledgements

- [x] I have looked for similar issues before submitting this one.
- [x] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [x] I understand that the developers have lives and my issue will be answered when possible.
- [x] I understand the developers of this program are human, and I will ask my questions politely.
