### ISSUE TITLE
[REQUEST] Breaking changes for configuration

### ISSUE THREAD

**Issue by kingbri1** [theroyallab/tabbyAPI#355]
### Problem

Inconsistency in config formats and users could not run some models out of the box

### Solution

1. Remove the `name` parameter when calling any load or switch endpoint
2. Fallback for `max_seq_len` is 4096, use `-1` if you want to read from `config.json`
3. Like config.yml, inline configs must have model-specific options must be nested under a `model:` top-level block

Please try the `breaking` branch to make sure everything works. These changes will be merged in the next few days, please update your inline configs.

### Explanation

Helps idiot-proof tabbyAPI for new users and removes legacy cruft + redundancies that aren't needed.

### Examples

Old inline config:

```yaml
max_seq_len: 8192
cache_size: Q4
draft_model:
  draft_rope_scale: 1.5
```

New inline config:

```yaml
model:
  max_seq_len: 8192
  cache_size: Q4
draft_model:
  draft_rope_scale: 1.5
```

### Acknowledgements

- [x] I have looked for similar requests before submitting this one.
- [x] I understand that the developers have lives and my issue will be answered when possible.
- [x] I understand the developers of this program are human, and I will make my requests politely.
